In [9]:
import math
import numpy as np

In [10]:
#Some Initial Parameters:
S0 = 36
K = 40
r = 0.06 #The rate of interest, or the risk-less short rate
T =1.0 #The time horizon and option maturity
sigma = 0.2 #Volatility
m = 3 #The number of time intervals; note that there will actually be m+1 periods as Python counts from 0

#Some Definitions:
dt = T / m #Length of each time interval
df = math.exp(-r * dt) #the discount favor for that fixed time interfal
up = math.exp(sigma*math.sqrt(dt))
down = 1 / up

q = (df - down) / (up-down) #The martingale probability of an upward movement

print(dt)
print(df)
print(up)
print(down)
print(q)


0.3333333333333333
0.9801986733067553
1.1224009024456676
0.8909472522884107
0.3856125014995631


In [11]:
S = np.zeros((m+1, m+1))
S[0, 0] = S0


z = 1
for t in range (1, m+1):
    for i in range (0, z):
        S[i, t] = S[i, t-1] *up
        S[i + 1, t] = S[i, t-1]*down
    z +=1

np.set_printoptions(formatter={'float_kind': lambda x: '%7.3f' %x})

print(S)

[[ 36.000  40.406  45.352  50.903]
 [  0.000  32.074  36.000  40.406]
 [  0.000   0.000  28.576  32.074]
 [  0.000   0.000   0.000  25.460]]


In [12]:
h = np.zeros_like(S)


K = 40
z=1
for t in range(0, m+1):
    for i in range(0, z):
        h[i, t] = max(K - S[i, t], 0)
    z += 1

print(h)

[[  4.000   0.000   0.000   0.000]
 [  0.000   7.926   4.000   0.000]
 [  0.000   0.000  11.424   7.926]
 [  0.000   0.000   0.000  14.540]]
